#ifndef _IRDECODER_H_
#define _IRDECODER_H_

#define USART_BAUD      (((F_CPU / (9600 * 16UL))) - 1)

#define STATE_NONE						0x00
#define STATE_RECEIVED_START_PULSE		0x01
#define STATE_RECEIVED_ADDRESS			0x02
#define STATE_RECEIVED_ADDR_INVERSE		0x03
#define STATE_RECEIVED_COMMAND			0x04
#define STATE_RECEIVED_COMMAND_INVERSE	0x05
#define STATE_SUCCESSFUL_READ			0x06

/* one millisecond of timer increments at each prescaler  */
#define ONE_MS_1024_PRESCALE	20
#define ONE_MS_256_PRESCALE		78
#define ONE_MS_64_PRESCALE		313
#define ONE_MS_8_PRESCALE		2500 /* 26ms overflow */

#define MAX_EDGES 			68
#define FULL_PACKET_EDGES	68
#define REPEAT_PACKET_EDGES	4

#define ERROR_MARGIN	0.05

/* 9ms start pulse */
#define NEC_START_PULSE_MIN				((ONE_MS_8_PRESCALE * 9) - (ONE_MS_8_PRESCALE * ERROR_MARGIN))
#define NEC_START_PULSE_MAX				((ONE_MS_8_PRESCALE * 9) + (ONE_MS_8_PRESCALE * ERROR_MARGIN))

#define NEC_POST_START_PAUSE_MIN		((ONE_MS_8_PRESCALE * 4.5) - (ONE_MS_8_PRESCALE * ERROR_MARGIN))
#define NEC_POST_START_PAUSE_MAX		((ONE_MS_8_PRESCALE * 4.5) + (ONE_MS_8_PRESCALE * ERROR_MARGIN))

#define NEC_BIT_PULSE_MIN				((ONE_MS_8_PRESCALE * 0.56) - (ONE_MS_8_PRESCALE * ERROR_MARGIN))
#define NEC_BIT_PULSE_MAX				((ONE_MS_8_PRESCALE * 0.56) + (ONE_MS_8_PRESCALE * ERROR_MARGIN))

#define NEC_1_BIT_TRANSMIT_TIME_MIN		((ONE_MS_8_PRESCALE * 1.125) - (ONE_MS_8_PRESCALE * ERROR_MARGIN))
#define NEC_1_BIT_TRANSMIT_TIME_MAX		((ONE_MS_8_PRESCALE * 2.25) + (ONE_MS_8_PRESCALE * ERROR_MARGIN))

/* command codes */
#define NEC_COMMAND_REPEAT	0xFF
#endif
